### ISSUE TITLE
Error in pretreatment of GREW

### ISSUE THREAD

**Issue by zhang123-sys** [ShiqiYu/OpenGait#110]
![image](https://user-images.githubusercontent.com/63956071/219368182-e255eb0f-4e20-4a90-9480-46ce3160165d.png)
Error when running"!python datasets/pretreatment.py --input_path /hy-nas/GREW-rearranged --output_path /hy-nas/GREW-pkl"

**Comment by zhang123-sys** [comment]
Pretreating:  11%|██                 | 1489/14132 [07:57<1:09:16,  3.04folder/s]multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "datasets/pretreatment.py", line 39, in imgs2pickle
    if img.sum() <= 10000:
AttributeError: 'NoneType' object has no attribute 'sum'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "datasets/pretreatment.py", line 150, in <module>
    pretreat(input_path=Path(args.input_path), output_path=Path(args.output_path), img_size=args.img_size, workers=args.n_workers, verbose=args.verbose, dataset=args.dataset)
  File "datasets/pretreatment.py", line 126, in pretreat
    for _ in pool.imap_unordered(partial(imgs2pickle, output_path=output_path, img_size=img_size, verbose=verbose, dataset=dataset), img_groups.items()):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
AttributeError: 'NoneType' object has no attribute 'sum'
Pretreating:  11%|██                 | 1491/14132 [07:59<1:07:46,  3.11folder/s]
