### ISSUE TITLE
GaitGL train and tesh CASIA-B: TypeError: object of type 'BaseSilCuttingTransform' has no len()

### ISSUE THREAD

**Issue by Morris-Lucifer** [ShiqiYu/OpenGait#114]
## System information (version)

- Pytorch =>  1.8.1+cu111 
- Operating System / Platform => Ubuntu 18.04.4 LTS
- Cuda => nvidia-smi: 11.2, nvcc -V: V9.1.85

## Detailed description
使用train.sh训练Baseline正常，注释Baseline训练命令，去掉GaitGL训练命令注释后出现问题，以下为log：
[2023-02-27 22:07:56] [INFO]: {'enable_float16': True, 'with_test': True, 'fix_BN': False, 'log_iter': 100, 'restore_ckpt_strict': True, 'optimizer_reset': False, 'scheduler_reset': False, 'restore_hint': 0, 'save_iter': 10000, 'save_name': 'GaitGL', 'sync_BN': True, 'total_iter': 80000, 'sampler': {'batch_shuffle': True, 'batch_size': [8, 8], 'frames_num_fixed': 30, 'frames_num_max': 50, 'frames_num_min': 25, 'sample_type': 'fixed_ordered', 'type': 'TripletSampler', 'frames_skip_num': 0}, 'transform': {'type': 'BaseSilCuttingTransform'}}
[2023-02-27 22:07:56] [INFO]: {'model': 'GaitGL', 'channels': [32, 64, 128], 'class_num': 74}
[2023-02-27 22:07:56] [INFO]: {'dataset_name': 'CASIA-B', 'dataset_root': '/home/username/OpenGait/datasets/CASIA-B/CASIA-B-pkl', 'num_workers': 1, 'dataset_partition': './datasets/CASIA-B/CASIA-B.json', 'remove_no_gallery': False, 'cache': False, 'test_dataset_name': 'CASIA-B'}
[2023-02-27 22:07:56] [INFO]: -------- Train Pid List --------
[2023-02-27 22:07:56] [INFO]: [001, 002, ..., 074]
[2023-02-27 22:07:56] [INFO]: -------- Test Pid List --------
[2023-02-27 22:07:56] [INFO]: [075, 076, ..., 124]
[2023-02-27 22:08:00] [INFO]: {'lr': 0.0001, 'momentum': 0.9, 'solver': 'Adam', 'weight_decay': 0.0005}
[2023-02-27 22:08:00] [INFO]: {'gamma': 0.1, 'milestones': [70000], 'scheduler': 'MultiStepLR'}
[2023-02-27 22:08:00] [INFO]: Parameters Count: 3.09667M
[2023-02-27 22:08:00] [INFO]: Model Initialization Finished!
Traceback (most recent call last):
  File "opengait/main.py", line 71, in <module>
    run_model(cfgs, training)
  File "opengait/main.py", line 54, in run_model
    Model.run_train(model)
  File "/home/username/OpenGait/opengait/modeling/base_model.py", line 404, in run_train
    ipts = model.inputs_pretreament(inputs)
  File "/home/username/OpenGait/opengait/modeling/base_model.py", line 304, in inputs_pretreament
    if len(seqs_batch) != len(seq_trfs):
TypeError: object of type 'BaseSilCuttingTransform' has no len()
Traceback (most recent call last):
  File "opengait/main.py", line 71, in <module>
    run_model(cfgs, training)
  File "opengait/main.py", line 54, in run_model
    Model.run_train(model)
  File "/home/username/OpenGait/opengait/modeling/base_model.py", line 404, in run_train
    ipts = model.inputs_pretreament(inputs)
  File "/home/username/OpenGait/opengait/modeling/base_model.py", line 304, in inputs_pretreament
    if len(seqs_batch) != len(seq_trfs):
***TypeError: object of type 'BaseSilCuttingTransform' has no len()***
Traceback (most recent call last):
  File "opengait/main.py", line 71, in <module>
    run_model(cfgs, training)
  File "opengait/main.py", line 54, in run_model
    Model.run_train(model)
  File "/home/username/OpenGait/opengait/modeling/base_model.py", line 404, in run_train
    ipts = model.inputs_pretreament(inputs)
  File "/home/username/OpenGait/opengait/modeling/base_model.py", line 304, in inputs_pretreament
Traceback (most recent call last):
    if len(seqs_batch) != len(seq_trfs):
TypeError: object of type 'BaseSilCuttingTransform' has no len()
  File "opengait/main.py", line 71, in <module>
    run_model(cfgs, training)
  File "opengait/main.py", line 54, in run_model
    Model.run_train(model)
  File "/home/username/OpenGait/opengait/modeling/base_model.py", line 404, in run_train
    ipts = model.inputs_pretreament(inputs)
  File "/home/username/OpenGait/opengait/modeling/base_model.py", line 304, in inputs_pretreament
    if len(seqs_batch) != len(seq_trfs):
***TypeError: object of type 'BaseSilCuttingTransform' has no len()***
Killing subprocess 23288
Killing subprocess 23289
Killing subprocess 23290
Killing subprocess 23291
Traceback (most recent call last):
  File "/home/username/.conda/envs/OpenGait/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/username/.conda/envs/OpenGait/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/username/.conda/envs/OpenGait/lib/python3.6/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/username/.conda/envs/OpenGait/lib/python3.6/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/username/.conda/envs/OpenGait/lib/python3.6/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/username/.conda/envs/OpenGait/bin/python', '-u', 'opengait/main.py', '--local_rank=3', '--cfgs', './configs/gaitgl/gaitgl.yaml', '--phase', 'train']' returned non-zero exit status 1.

## Others
显卡型号数量：RTX3080*4
已下载预训练模型
train.sh和test.sh中除增减#号未进行其他更改，报错log相同
尝试Issues #15 更改config和batch_size 报错log相同

## Issue submission checklist
 - [x] I checked the problem with documentation, ~~FAQ~~(didn't find), issues, and have not found solution.

**Comment by darkliang** [comment]
Please check `transform` in your config file. `transform` should contain a list of `transform function`.

**Comment by Morris-Lucifer** [comment]
现在GaitGL可以正常训练了，感谢您的及时回复！
