### ISSUE TITLE
Error when training grew using gaitbase

### ISSUE THREAD

**Issue by zhang123-sys** [ShiqiYu/OpenGait#125]
## System information (version)
OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.9

Python version: 3.6.4 |Anaconda, Inc.| (default, Mar 13 2018, 01:15:57)  [GCC 7.2.0] (64-bit runtime)
Python platform: Linux-4.15.0-167-generic-x86_64-with-debian-bullseye-sid
Is CUDA available: True
CUDA runtime version: 11.3.109
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3090
Nvidia driver version: 470.82.01

## Detailed description

Error when running "CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node=1 opengait/main.py --cfgs ./configs/gaitbase/gaitbase_da_grew.yaml --phase train"

**Comment by darkliang** [comment]
Please provide detailed error information.

**Comment by zhang123-sys** [comment]
(openGait) ***@***.***:/hy-nas/OpenGait# CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node=1 opengait/main.py --cfgs ./configs/gaitbase/gaitbase_da_grew.yaml --phase train
/usr/local/miniconda3/envs/openGait/lib/python3.6/site-packages/torch/distributed/launch.py:186: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See&nbsp;
https://pytorch.org/docs/stable/distributed.html#launch-utility for&nbsp;
further instructions


&nbsp; FutureWarning,
[2023-04-13 18:47:05] [INFO]: {'enable_float16': True, 'with_test': False, 'fix_BN': False, 'log_iter': 100, 'restore_ckpt_strict': True, 'optimizer_reset': False, 'scheduler_reset': False, 'restore_hint': 180000, 'save_iter': 5000, 'save_name': 'GaitBase_DA', 'sync_BN': True, 'total_iter': 220000, 'sampler': {'batch_shuffle': True, 'batch_size': [32, 4], 'frames_num_fixed': 30, 'frames_num_max': 40, 'frames_num_min': 20, 'sample_type': 'unfixed_unordered', 'type': 'TripletSampler'}, 'transform': [{'type': 'Compose', 'trf_cfg': [{'type': 'RandomPerspective', 'prob': 0.2}, {'type': 'BaseSilCuttingTransform'}, {'type': 'RandomHorizontalFlip', 'prob': 0.2}, {'type': 'RandomRotate', 'prob': 0.2}]}]}
[2023-04-13 18:47:05] [INFO]: {'model': 'Baseline', 'backbone_cfg': {'type': 'ResNet9', 'block': 'BasicBlock', 'channels': [64, 128, 256, 512], 'layers': [1, 1, 1, 1], 'strides': [1, 2, 2, 1], 'maxpool': False}, 'SeparateFCs': {'in_channels': 512, 'out_channels': 256, 'parts_num': 16}, 'SeparateBNNecks': {'class_num': 20000, 'in_channels': 256, 'parts_num': 16}, 'bin_num': [16]}
[2023-04-13 18:47:06] [INFO]: {'dataset_name': 'HID', 'dataset_root': '/hy-nas/OpenGait/HID2022/HID-128-pkl', 'num_workers': 1, 'dataset_partition': './datasets/HID/HID.json', 'remove_no_gallery': False, 'cache': False, 'test_dataset_name': 'CASIA-B'}
[2023-04-13 18:47:06] [INFO]: -------- Train Pid List --------
[2023-04-13 18:47:06] [INFO]: [0008, 0013, ..., 0486]
[2023-04-13 18:47:13] [INFO]: {'lr': 0.1, 'momentum': 0.9, 'solver': 'SGD', 'weight_decay': 0.0005}
[2023-04-13 18:47:13] [INFO]: {'gamma': 0.1, 'milestones': [190000, 200000, 210000], 'scheduler': 'MultiStepLR'}
[2023-04-13 18:47:14] [WARNING]: Restore NO Optimizer from output/HID/Baseline/GaitBase_DA/checkpoints/GaitBase_DA-180000.pt !!!
[2023-04-13 18:47:14] [INFO]: Restore Parameters from output/GREW/Baseline/GaitBase_DA/checkpoints/GaitBase_DA-180000.pt !!!
[2023-04-13 18:47:14] [INFO]: Parameters Count: 88.92230M
[2023-04-13 18:47:14] [INFO]: Model Initialization Finished!
Traceback (most recent call last):
&nbsp; File "opengait/main.py", line 71, in <module&gt;
&nbsp; &nbsp; run_model(cfgs, training)
&nbsp; File "opengait/main.py", line 54, in run_model
&nbsp; &nbsp; Model.run_train(model)
&nbsp; File "/hy-nas/OpenGait/opengait/modeling/base_model.py", line 406, in run_train
&nbsp; &nbsp; retval = model(ipts)
&nbsp; File "/usr/local/miniconda3/envs/openGait/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
&nbsp; &nbsp; return forward_call(*input, **kwargs)
&nbsp; File "/usr/local/miniconda3/envs/openGait/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 886, in forward
&nbsp; &nbsp; output = self.module(*inputs[0], **kwargs[0])
&nbsp; File "/usr/local/miniconda3/envs/openGait/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
&nbsp; &nbsp; return forward_call(*input, **kwargs)
&nbsp; File "/hy-nas/OpenGait/opengait/modeling/models/baseline.py", line 25, in forward
&nbsp; &nbsp; outs = self.Backbone(sils)&nbsp; # [n, c, s, h, w]
&nbsp; File "/usr/local/miniconda3/envs/openGait/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
&nbsp; &nbsp; return forward_call(*input, **kwargs)
&nbsp; File "/hy-nas/OpenGait/opengait/modeling/modules.py", line 47, in forward
&nbsp; &nbsp; 1, 2).reshape(-1, c, h, w), *args, **kwargs)
&nbsp; File "/usr/local/miniconda3/envs/openGait/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
&nbsp; &nbsp; return forward_call(*input, **kwargs)
&nbsp; File "/hy-nas/OpenGait/opengait/modeling/backbones/resnet.py", line 48, in forward
&nbsp; &nbsp; x = self.bn1(x)
&nbsp; File "/usr/local/miniconda3/envs/openGait/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
&nbsp; &nbsp; return forward_call(*input, **kwargs)
&nbsp; File "/usr/local/miniconda3/envs/openGait/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 745, in forward
&nbsp; &nbsp; self.eps,
&nbsp; File "/usr/local/miniconda3/envs/openGait/lib/python3.6/site-packages/torch/nn/functional.py", line 2283, in batch_norm
&nbsp; &nbsp; input, weight, bias, running_mean, running_var, training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2080) of binary: /usr/local/miniconda3/envs/openGait/bin/python
Traceback (most recent call last):
&nbsp; File "/usr/local/miniconda3/envs/openGait/lib/python3.6/runpy.py", line 193, in _run_module_as_main
&nbsp; &nbsp; "__main__", mod_spec)
&nbsp; File "/usr/local/miniconda3/envs/openGait/lib/python3.6/runpy.py", line 85, in _run_code
&nbsp; &nbsp; exec(code, run_globals)
&nbsp; File "/usr/local/miniconda3/envs/openGait/lib/python3.6/site-packages/torch/distributed/launch.py", line 193, in <module&gt;
&nbsp; &nbsp; main()
&nbsp; File "/usr/local/miniconda3/envs/openGait/lib/python3.6/site-packages/torch/distributed/launch.py", line 189, in main
&nbsp; &nbsp; launch(args)
&nbsp; File "/usr/local/miniconda3/envs/openGait/lib/python3.6/site-packages/torch/distributed/launch.py", line 174, in launch
&nbsp; &nbsp; run(args)
&nbsp; File "/usr/local/miniconda3/envs/openGait/lib/python3.6/site-packages/torch/distributed/run.py", line 713, in run
&nbsp; &nbsp; )(*cmd_args)
&nbsp; File "/usr/local/miniconda3/envs/openGait/lib/python3.6/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
&nbsp; &nbsp; return launch_agent(self._config, self._entrypoint, list(args))
&nbsp; File "/usr/local/miniconda3/envs/openGait/lib/python3.6/site-packages/torch/distributed/launcher/api.py", line 261, in launch_agent
&nbsp; &nbsp; failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:&nbsp;
============================================================
opengait/main.py FAILED
------------------------------------------------------------
Failures:
&nbsp; <NO_OTHER_FAILURES&gt;
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
&nbsp; time&nbsp; &nbsp; &nbsp; : 2023-04-13_18:47:19
&nbsp; host&nbsp; &nbsp; &nbsp; : I11e8eb756600b01f2a
&nbsp; rank&nbsp; &nbsp; &nbsp; : 0 (local_rank: 0)
&nbsp; exitcode&nbsp; : 1 (pid: 2080)
&nbsp; error_file: <N/A&gt;
&nbsp; traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Junhao ***@***.***&gt;; 
发送时间: 2023年4月13日(星期四) 晚上7:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ShiqiYu/OpenGait] Error when training grew using gaitbase (Issue #125)





 
Please provide detailed error information.

**Comment by darkliang** [comment]
Most likely it's out of memory.

**Comment by zhang123-sys** [comment]
> Most likely it's out of memory.

Excuse me, I test grew using gaitbase, but error when running "CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node=1 opengait/main.py --cfgs ./configs/gaitbase/gaitbase_da_grew.yaml --phase test"

![image](https://github.com/ShiqiYu/OpenGait/assets/63956071/0ccccf94-eff6-49e0-a272-23e1438aedbb)
the log is below
(openGait) root@:/hy-nas/OpenGait# CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node=1 opengait/main.py --cfgs ./configs/gaitbase/gaitbase_da_grew.yaml --phase test
/usr/local/miniconda3/envs/openGait/lib/python3.6/site-packages/torch/distributed/launch.py:186: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  FutureWarning,
[2023-05-17 08:25:51] [INFO]: {'enable_float16': True, 'restore_ckpt_strict': True, 'restore_hint': 180000, 'save_name': 'GaitBase_DA', 'eval_func': 'GREW_submission', 'sampler': {'batch_size': 16, 'sample_type': 'all_ordered', 'type': 'InferenceSampler', 'batch_shuffle': False, 'frames_all_limit': 720}, 'transform': [{'type': 'BaseSilCuttingTransform'}], 'metric': 'euc', 'cross_view_gallery': False}
[2023-05-17 08:25:51] [INFO]: {'model': 'Baseline', 'backbone_cfg': {'type': 'ResNet9', 'block': 'BasicBlock', 'channels': [64, 128, 256, 512], 'layers': [1, 1, 1, 1], 'strides': [1, 2, 2, 1], 'maxpool': False}, 'SeparateFCs': {'in_channels': 512, 'out_channels': 256, 'parts_num': 16}, 'SeparateBNNecks': {'class_num': 20000, 'in_channels': 256, 'parts_num': 16}, 'bin_num': [16]}
[2023-05-17 08:25:52] [INFO]: {'dataset_name': 'GREW', 'dataset_root': '/hy-nas/GREW-pkl', 'num_workers': 1, 'dataset_partition': './datasets/GREW/GREW.json', 'remove_no_gallery': False, 'cache': False, 'test_dataset_name': 'GREW'}
[2023-05-17 08:25:52] [INFO]: -------- Test Pid List --------
[2023-05-17 08:25:52] [INFO]: [00001, 00002, ..., 00412]
[2023-05-17 08:25:59] [INFO]: Restore Parameters from output/GREW/Baseline/GaitBase_DA/checkpoints/GaitBase_DA-180000.pt !!!
[2023-05-17 08:25:59] [INFO]: Parameters Count: 88.92230M
[2023-05-17 08:25:59] [INFO]: Model Initialization Finished!
Transforming:  99%|███████████████████████████████████████████████████████████████████████████████████████████████████▏| 816/823 [00:13<00:00, 53.30it/s]Traceback (most recent call last):
  File "opengait/main.py", line 71, in <module>
    run_model(cfgs, training)
  File "opengait/main.py", line 56, in run_model
    Model.run_test(model)
  File "/hy-nas/OpenGait/opengait/modeling/base_model.py", line 442, in run_test
    info_dict = model.inference(rank)
  File "/hy-nas/OpenGait/opengait/modeling/base_model.py", line 377, in inference
    for inputs in self.test_loader:
  File "/usr/local/miniconda3/envs/openGait/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/usr/local/miniconda3/envs/openGait/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/usr/local/miniconda3/envs/openGait/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/usr/local/miniconda3/envs/openGait/lib/python3.6/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
EOFError: Caught EOFError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/miniconda3/envs/openGait/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/miniconda3/envs/openGait/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/miniconda3/envs/openGait/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/hy-nas/OpenGait/opengait/data/dataset.py", line 56, in __getitem__
    data_list = self.__loader__(self.seqs_info[idx][-1])
  File "/hy-nas/OpenGait/opengait/data/dataset.py", line 40, in __loader__
    _ = pickle.load(f)
EOFError: Ran out of input

Transforming:  99%|███████████████████████████████████████████████████████████████████████████████████████████████████▏| 816/823 [00:13<00:00, 58.65it/s]
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 668) of binary: /usr/local/miniconda3/envs/openGait/bin/python
Traceback (most recent call last):
  File "/usr/local/miniconda3/envs/openGait/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/miniconda3/envs/openGait/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/miniconda3/envs/openGait/lib/python3.6/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/usr/local/miniconda3/envs/openGait/lib/python3.6/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/usr/local/miniconda3/envs/openGait/lib/python3.6/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/usr/local/miniconda3/envs/openGait/lib/python3.6/site-packages/torch/distributed/run.py", line 713, in run
    )(*cmd_args)
  File "/usr/local/miniconda3/envs/openGait/lib/python3.6/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/miniconda3/envs/openGait/lib/python3.6/site-packages/torch/distributed/launcher/api.py", line 261, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
opengait/main.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-05-17_08:26:14
  host      : I12a38ab02600e01601
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 668)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by chuanfushen** [comment]
Look like the pickle is empty.
you might check: https://stackoverflow.com/questions/24791987/why-do-i-get-pickle-eoferror-ran-out-of-input-reading-an-empty-file

find this empty pickle and check wether you download the right dataset and process it correctly.

**Comment by zhang123-sys** [comment]
thanks



---Original---
From: ***@***.***&gt;
Date: Sat, Jul 15, 2023 17:43 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ShiqiYu/OpenGait] Error when training grew using gaitbase (Issue#125)




 
Look like the pickle is empty.
 you might check: https://stackoverflow.com/questions/24791987/why-do-i-get-pickle-eoferror-ran-out-of-input-reading-an-empty-file
 
find this empty pickle and check wether you download the right dataset and process it correctly.
