### ISSUE TITLE
TypeError: expected np.ndarray (got Odict), When run GaitEdge->"phase1_seg.yaml"

### ISSUE THREAD

**Issue by hxi667** [ShiqiYu/OpenGait#127]
When I execute the "CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --master_port=21231 --nproc_per_node=2 opengait/main.py --cfgs ./configs/gaitedge/phase1_seg.yaml --phase train --log_to_file" command , I get an error:

[2023-04-17 17:30:03] [INFO]: Running test...
Transforming: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5496/5496 [05:09<00:00, 17.77it/s]
Traceback (most recent call last):
  File "opengait/main.py", line 74, in <module>
    run_model(cfgs, training)
  File "opengait/main.py", line 54, in run_model
    Model.run_train(model)
  File "/root/data/hxi/GaitRecognition/Code/OpenGait/opengait/modeling/base_model.py", line 426, in run_train
    result_dict = BaseModel.run_test(model)
  File "/root/data/hxi/GaitRecognition/Code/OpenGait/opengait/modeling/base_model.py", line 463, in run_test
    return eval_func(info_dict, dataset_name, **valid_args)
  File "/root/data/hxi/GaitRecognition/Code/OpenGait/opengait/evaluation/metric.py", line 32, in mean_iou
    msk1 = torch.from_numpy(msk1).cuda()
TypeError: expected np.ndarray (got Odict)

I guess the error should have occurred during the testing phase.

Attached is my configuration file "phase1_seg.yaml":
[phase1_seg.yaml.txt](https://github.com/ShiqiYu/OpenGait/files/11248714/phase1_seg.yaml.txt)

**Comment by darkliang** [comment]
Thanks for reporting this issue, just fixed in d5b1ae3.

**Comment by hxi667** [comment]
Thank you for the prompt fix!
