### ISSUE TITLE
Error occurrs when test gaitGL with CASIA-B dataset 

### ISSUE THREAD

**Issue by foolishman-wx** [ShiqiYu/OpenGait#15]
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
[2021-11-13 15:04:55] [INFO]: {'enable_float16': False, 'restore_ckpt_strict': True, 'restore_hint': 80000, 'save_name': 'GaitGL', 'eval_func': 'identification', 'sampler': {'batch_size': 4, 'sample_type': 'all_ordered', 'type': 'InferenceSampler'}, 'transform': [{'img_w': 64, 'type': 'BaseSilCuttingTransform'}], 'metric': 'euc', 'enable_distributed': True}
[2021-11-13 15:04:55] [INFO]: {'model': 'GaitGL', 'channels': [32, 64, 128], 'class_num': 74}
[2021-11-13 15:04:55] [INFO]: {'dataset_name': 'CASIA-B', 'dataset_root': '/media/yangxilab/DiskB1/wxian/dataset/CASIA-B/CASIA-B-pkl/', 'num_workers': 1, 'dataset_partition': './misc/partitions/CASIA-B_include_005.json', 'remove_no_gallery': False, 'cache': False, 'test_dataset_name': 'CASIA-B'}
[2021-11-13 15:04:55] [INFO]: -------- Test Pid List --------
[2021-11-13 15:04:55] [INFO]: [075, 076, ..., 124]
[2021-11-13 15:04:56] [INFO]: Restore Parameters from output/CASIA-B/GaitGL/GaitGL/checkpoints/GaitGL-80000.pt !!!
[2021-11-13 15:04:58] [INFO]: Parameters Count: 3.09667M
[2021-11-13 15:04:58] [INFO]: Model Initialization Finished!
Transforming: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5485/5485 [01:24<00:00, 64.84it/s]
Traceback (most recent call last):
  File "lib/main.py", line 66, in <module>
    run_model(cfgs, training)
  File "lib/main.py", line 51, in run_model
    Model.run_test(model)
  File "/media/yangxilab/DiskB1/wxian/dataset/OpenGait-master/lib/modeling/base_model.py", line 417, in run_test
    return eval_func(info_dict, dataset_name, **valid_args)
  File "/media/yangxilab/DiskB1/wxian/dataset/OpenGait-master/lib/utils/evaluation.py", line 67, in identification
    gallery_x = feature[gseq_mask, :]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 2744 but corresponding boolean dimension is 5485

It is normal when testing other models, such as GAITSET, but there is a problem when testing GAITGL. i don't know why ?

**Comment by darkliang** [comment]
@foolishman-wx See https://github.com/ShiqiYu/OpenGait/issues/4
