### ISSUE TITLE
Error when test on centos 

### ISSUE THREAD

**Issue by zhang123-sys** [ShiqiYu/OpenGait#153]
Runtime Environment: python 3.9 pytorch 1.13 
Linux version: centos7
test gaitbase model on GREW dataset
Error:
warnings.warn(
Traceback (most recent call last):
  File "/data1/OpenGait/opengait/main.py", line 60, in <module>
    torch.distributed.init_process_group('nccl', init_method='env://')
  File "/opt/anaconda3/envs/openGait/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 764, in init_process_group
    default_pg = _new_process_group_helper(
  File "/opt/anaconda3/envs/openGait/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 889, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL " "built in")
RuntimeError: Distributed package doesn't have NCCL built in
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 73954) of binary: /opt/anaconda3/envs/openGait/bin/python
Traceback (most recent call last):
  File "/opt/anaconda3/envs/openGait/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/anaconda3/envs/openGait/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/anaconda3/envs/openGait/lib/python3.9/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/opt/anaconda3/envs/openGait/lib/python3.9/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/opt/anaconda3/envs/openGait/lib/python3.9/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/opt/anaconda3/envs/openGait/lib/python3.9/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/opt/anaconda3/envs/openGait/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/anaconda3/envs/openGait/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
opengait/main.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-08-29_10:48:40
  host      : localhost.localdomain
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 73954)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by zhang123-sys** [comment]
environment
torch                    1.13.1
torchvision              0.14.1

**Comment by updatelse** [comment]
这个好像是怪分布式的原因

**Comment by zhang123-sys** [comment]
谢谢，训练不支持多GPU？



---Original---
From: ***@***.***&gt;
Date: Tue, Sep 5, 2023 09:43 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ShiqiYu/OpenGait] Error when test on centos  (Issue #153)




 
这个好像是怪分布式的原因

**Comment by zhang123-sys** [comment]
Error when test gaitbase on CASIA-E

**Comment by zhang123-sys** [comment]
CUDA_VISIBLE_DEVICES=1 python -m torch.distributed.launch --nproc_per_node=1 --master_port=1251 opengait/main.py --cfgs ./configs/gaitbase/gaitbase_casiae.yaml --phase test
(OpenGait_py3.6) [root@localhost OpenGait]# ./CASIA-E.sh
/opt/anaconda3/envs/OpenGait_py3.6/lib/python3.6/site-packages/torch/distributed/launch.py:186: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  FutureWarning,
[2023-09-13 16:52:22] [INFO]: {'enable_float16': True, 'restore_ckpt_strict': True, 'restore_hint': 60000, 'save_name': 'GaitBase', 'eval_func': 'evaluate_indoor_dataset', 'sampler': {'batch_size': 16, 'sample_type': 'all_ordered', 'type': 'InferenceSampler', 'batch_shuffle': False, 'frames_all_limit': 720}, 'transform': [{'type': 'BaseSilCuttingTransform'}], 'metric': 'euc', 'cross_view_gallery': False}
[2023-09-13 16:52:22] [INFO]: {'model': 'Baseline', 'backbone_cfg': {'type': 'ResNet9', 'block': 'BasicBlock', 'channels': [64, 128, 256, 512], 'layers': [1, 1, 1, 1], 'strides': [1, 2, 2, 1], 'maxpool': False}, 'SeparateFCs': {'in_channels': 512, 'out_channels': 256, 'parts_num': 16}, 'SeparateBNNecks': {'class_num': 200, 'in_channels': 256, 'parts_num': 16}, 'bin_num': [16]}
[2023-09-13 16:52:22] [INFO]: {'dataset_name': 'CASIA-E', 'dataset_root': '/data1/CASIA-E-processed', 'num_workers': 1, 'dataset_partition': './datasets/CASIA-E/CASIA-E.json', 'remove_no_gallery': False, 'cache': False, 'test_datase[2023-09-13 16:52:45] [INFO]: Parameters Count: 7.82150M
[2023-09-13 16:52:45] [INFO]: Model Initialization Finished!
Transforming: 0it [00:00, ?it/s]
Traceback (most recent call last):
  File "opengait/main.py", line 75, in <module>
    run_model(cfgs, training)
  File "opengait/main.py", line 60, in run_model
    Model.run_test(model)
  File "/data1/OpenGait/opengait/modeling/base_model.py", line 463, in run_test
    return eval_func(info_dict, dataset_name, **valid_args)
  File "/data1/OpenGait/opengait/evaluation/evaluator.py", line 134, in evaluate_indoor_dataset
    feature, label, seq_type, view = data['embeddings'], data['labels'], data['types'], data['views']
KeyError: 'embeddings'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 78551) of binary: /opt/anaconda3/envs/OpenGait_py3.6/bin/python
Traceback (most recent call last):
  File "/opt/anaconda3/envs/OpenGait_py3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/anaconda3/envs/OpenGait_py3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/anaconda3/envs/OpenGait_py3.6/lib/python3.6/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/opt/anaconda3/envs/OpenGait_py3.6/lib/python3.6/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/opt/anaconda3/envs/OpenGait_py3.6/lib/python3.6/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/opt/anaconda3/envs/OpenGait_py3.6/lib/python3.6/site-packages/torch/distributed/run.py", line 713, in run
    )(*cmd_args)
  File "/opt/anaconda3/envs/OpenGait_py3.6/lib/python3.6/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/anaconda3/envs/OpenGait_py3.6/lib/python3.6/site-packages/torch/distributed/launcher/api.py", line 261, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
opengait/main.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-09-13_16:52:48
  host      : localhost.localdomain
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 78551)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by zhang123-sys** [comment]
> Error when test gaitbase on CASIA-E

KeyError: 'embeddings'

**Comment by zhang123-sys** [comment]
Can OpenGait work on Windows 11 with a RTX3050Ti gpu?
