### ISSUE TITLE
Training Issue for CPU/GPU

### ISSUE THREAD

**Issue by EshaalFatima01** [ShiqiYu/OpenGait#157]
# Hello, please guide me to solve this error on google colab

**/usr/local/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:

Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 

/usr/local/bin/python: can't open file 'opengait/main.py': [Errno 2] No such file or directory
/usr/local/bin/python: can't open file 'opengait/main.py': [Errno 2] No such file or directory
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 2) local_rank: 0 (pid: 21458) of binary: /usr/local/bin/python
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/usr/local/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/usr/local/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/usr/local/lib/python3.8/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/usr/local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 

opengait/main.py FAILED

Failures:
[1]:
  time      : 2023-09-18_06:53:26
  host      : a7867dc7575a
  rank      : 1 (local_rank: 1)
  exitcode  : 2 (pid: 21459)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

Root Cause (first observed failure):
[0]:
  time      : 2023-09-18_06:53:26
  host      : a7867dc7575a
  rank      : 0 (local_rank: 0)
  exitcode  : 2 (pid: 21458)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html**

**Comment by EshaalFatima01** [comment]
### **When I am running this code on my laptop having this error**

**[W C:\b\abs_abjetg6_iu\croot\pytorch_1686932924616\work\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [LENOVO-PC]:23456 (system error: 10049 - The requested address is not valid in its context.).
Traceback (most recent call last):
  File "main.py", line 62, in <module>
    torch.distributed.init_process_group(backend='gloo', init_method='env://')
  File "D:\Anaconda\envs\OpenGait\lib\site-packages\torch\distributed\distributed_c10d.py", line 900, in init_process_group**

**Comment by darkliang** [comment]
`/usr/local/bin/python: can't open file 'opengait/main.py': [Errno 2] No such file or directory` which should be the actual error.
