### ISSUE TITLE
Training issues with gaitgraph1

### ISSUE THREAD

**Issue by fffaaaaaa** [ShiqiYu/OpenGait#161]
class JointNoise(object):
"""
Add Gaussian noise to joint
std: standard deviation
"""

def __init__(self, std=0.25):
    self.std = std

def __call__(self, data):
    # T, V, C
    noise = np.hstack((
        np.random.normal(0, self.std, (data.shape[1], 2)),
        np.zeros((data.shape[1], 1))
    )).astype(np.float32)

    return data + np.repeat(noise[np.newaxis, ...], data.shape[0], axis=0)
    报错
    Traceback (most recent call last):
File "D:\gait recognition\OpenGait-master_new\opengait\main.py", line 72, in
run_model(cfgs, training)
File "D:\gait recognition\OpenGait-master_new\opengait\main.py", line 54, in run_model
Model.run_train(model)
File "D:\gait recognition\OpenGait-master_new\opengait\modeling\base_model.py", line 406, in run_train
ipts = model.inputs_pretreament(inputs)
File "D:\gait recognition\OpenGait-master_new\opengait\modeling\base_model.py", line 310, in inputs_pretreament
seqs = [np2var(np.asarray([trf(fra) for fra in seq]), requires_grad=requires_grad).float()
File "D:\gait recognition\OpenGait-master_new\opengait\modeling\base_model.py", line 310, in
seqs = [np2var(np.asarray([trf(fra) for fra in seq]), requires_grad=requires_grad).float()
File "D:\gait recognition\OpenGait-master_new\opengait\modeling\base_model.py", line 310, in
seqs = [np2var(np.asarray([trf(fra) for fra in seq]), requires_grad=requires_grad).float()
File "D:\Users\15840\anaconda3\envs\py39\lib\site-packages\torchvision\transforms\transforms.py", line 94, in call
img = t(img)
File "D:\gait recognition\OpenGait-master_new\opengait\data\transform.py", line 339, in call
return data + np.repeat(noise[np.newaxis, ...], data.shape[0], axis=0)
ValueError: operands could not be broadcast together with shapes (60,64,44) (60,64,3)
有大佬知道怎么修改吗

**Comment by jdyjjj** [comment]
GaitGraph1 is a pose based method. It seems that you use silhouette dataset. You can see how to pretreat the pose dataset. Good luck.

**Comment by fffaaaaaa** [comment]
Thank you
