### ISSUE TITLE
使用提供的权重运行GaitGL时，出现问题

### ISSUE THREAD

**Issue by zhangzhi-git** [ShiqiYu/OpenGait#17]
*****************************************
[2021-12-02 19:53:48] [INFO]: {'enable_float16': False, 'restore_ckpt_strict': True, 'restore_hint': 80000, 'save_name': 'GaitGL', 'eval_func': 'identification', 'sampler': {'batch_size': 4, 'sample_type': 'all_ordered', 'type': 'InferenceSampler'}, 'transform': [{'img_w': 64, 'type': 'BaseSilCuttingTransform'}], 'metric': 'euc', 'enable_distributed': True}
[2021-12-02 19:53:48] [INFO]: {'model': 'GaitGL', 'channels': [32, 64, 128], 'class_num': 74}
[2021-12-02 19:53:48] [INFO]: {'dataset_name': 'CASIA-B', 'dataset_root': 'xxxxxi/datasets/Gait/CASIA-B/opengait-64', 'num_workers': 1, 'dataset_partition': './misc/partitions/CASIA-B_include_005.json', 'remove_no_gallery': False, 'cache': False, 'test_dataset_name': 'CASIA-B', 'pid_num': 74}
[2021-12-02 19:53:48] [INFO]: -------- Test Pid List --------
[2021-12-02 19:53:48] [INFO]: [075, 076, ..., 124]
[2021-12-02 19:53:53] [INFO]: Restore Parameters from xxxxxi/GaitGL/GaitGL/checkpoints/GaitGL-80000.pt !!!
[2021-12-02 19:53:53] [INFO]: Parameters Count: 3.09667M
[2021-12-02 19:53:53] [INFO]: Model Initialization Finished!
Transforming: 100%|█████████████████████████| 5485/5485 [01:05<00:00, 84.04it/s]
Traceback (most recent call last):
  File "lib/main.py", line 66, in <module>
    run_model(cfgs, training)
  File "lib/main.py", line 51, in run_model
    Model.run_test(model)
  File "/home/xxxxxi/project/Gait/OpenGait/lib/modeling/base_model.py", line 423, in run_test
    return eval_func(info_dict, dataset_name, **valid_args)
  File "/home/xxxxxi/project/Gait/OpenGait/lib/utils/evaluation.py", line 67, in identification
    gallery_x = feature[gseq_mask, :]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 2744 but corresponding boolean dimension is 5485
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 230780) of binary: /usr/local/anaconda3/bin/python3.8
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/xxxxxi/.local/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/xxxxxi/.local/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/xxxxxi/.local/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/xxxxxi/.local/lib/python3.8/site-packages/torch/distributed/run.py", line 689, in run
    elastic_launch(
  File "/home/xxxxxi/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 116, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/xxxxxi/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 244, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
***************************************
           lib/main.py FAILED          
=======================================
Root Cause:
[0]:
  time: 2021-12-02_19:55:02
  rank: 0 (local_rank: 0)
  exitcode: 1 (pid: 230780)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
=======================================
Other Failures:
  <NO_OTHER_FAILURES>
***************************************

**Comment by noahshen98** [comment]
pls paste error information, then we could provide assistance.

**Comment by noahshen98** [comment]
I guess you may meet identical problem like #4.

**Comment by zhangzhi-git** [comment]
> I guess you may meet identical problem like #4.
非常抱歉，打扰到您，您回复的非常及时。我想知道我这是大概遇到了什么问题？

**Comment by noahshen98** [comment]
> I guess you may meet identical problem like #4.
> 非常抱歉，打扰到您，您回复的非常及时。我想知道我这是大概遇到了什么问题？

GaitGL的测试时，需要满足evaluator_cfg下的sampler  的 batch_size与你使用的GPU数量相同。

假设你只有一张卡，需要修改`gaitgl.yaml`下的
```
evaluator_cfg:
  enable_distributed: true
  enable_float16: false 
  restore_ckpt_strict: true
  restore_hint: 80000
  save_name: GaitGL
  sampler:
    batch_size: 1
    sample_type: all_ordered
    type: InferenceSampler
```

然后运行：
```
CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --master_port 12345 --nproc_per_node=1 lib/main.py --cfgs ./config/gaitgl.yaml --iter 80000 --phase test
```

**Comment by zhangzhi-git** [comment]
是我大意了，没有仔细注意您们工作细节，感谢您，回复效率真快，快的我都想给你转账🥰。感谢您，感谢您！！！

**Comment by Xiloy** [comment]
你好，哪里有提供权重了？我没找到。。
