### ISSUE TITLE
GREW_pose to heatmap error 

### ISSUE THREAD

**Issue by YingQQ666** [ShiqiYu/OpenGait#222]
按照Readme的指示，将GREW的pose数据转为heatmap，但是报下面的错误。 transfer_to_coco17设的是False。请问是哪里出了问题？

(opengait) [root@xyq opengait-gitee]# CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.run --nproc_per_node=2 datasets/pretreatment_heatmap.py --pose_data_path /home/datasets/GREW_pose_pkl/ --save_root /home/datasets/GREW_heatmap/ --dataset_name grew
WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
  0%|                                                                                                                                                                               | 0/63444 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "/home/code/opengait-gitee/datasets/pretreatment_heatmap.py", line 709, in <module>
    for _, tmp in tqdm(enumerate(dataloader), total=len(dataloader)):
  File "/root/anaconda3/envs/opengait/lib/python3.9/site-packages/tqdm/std.py", line 1182, in __iter__
    for obj in iterable:
  File "/root/anaconda3/envs/opengait/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/root/anaconda3/envs/opengait/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/root/anaconda3/envs/opengait/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/root/anaconda3/envs/opengait/lib/python3.9/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/anaconda3/envs/opengait/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/anaconda3/envs/opengait/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/anaconda3/envs/opengait/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/code/opengait-gitee/datasets/pretreatment_heatmap.py", line 634, in __getitem__
    pose_data = pose_data[:,2:].reshape(-1, 17, 3)
ValueError: cannot reshape array of size 4320 into shape (17,3)

  0%|                                                                                                                                                                               | 0/63444 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "/home/code/opengait-gitee/datasets/pretreatment_heatmap.py", line 709, in <module>
    for _, tmp in tqdm(enumerate(dataloader), total=len(dataloader)):
  File "/root/anaconda3/envs/opengait/lib/python3.9/site-packages/tqdm/std.py", line 1182, in __iter__
    for obj in iterable:
  File "/root/anaconda3/envs/opengait/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/root/anaconda3/envs/opengait/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/root/anaconda3/envs/opengait/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/root/anaconda3/envs/opengait/lib/python3.9/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/anaconda3/envs/opengait/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/anaconda3/envs/opengait/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/anaconda3/envs/opengait/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/code/opengait-gitee/datasets/pretreatment_heatmap.py", line 634, in __getitem__
    pose_data = pose_data[:,2:].reshape(-1, 17, 3)
ValueError: cannot reshape array of size 2655 into shape (17,3)

**Comment by jdyjjj** [comment]
What is the specific format of your GREW pose data? Is it preprocessed pose data? I hope you can double check.

**Comment by YingQQ666** [comment]
> What is the specific format of your GREW pose data? Is it preprocessed pose data? I hope you can double check.

我是在是官方给的下载链接里下载解压的，里面有siles.png和pose.txt的数据，然后按照教程rearrange,pretreatment得到pkl文件。难道不是这样的步骤吗？
