### ISSUE TITLE
Problem about the given GaitGL-OUMVLP model

### ISSUE THREAD

**Issue by ctrasd** [ShiqiYu/OpenGait#31]
We test the given GaitGL model directly on OUMVLP dataset, but it can't ahcieve 89.9% at Rank@1(excluding identical-view cases). 

The results are:
 ===Rank-1 (Include identical-view cases)===
NM: 89.914 
===Rank-1 (Exclude identical-view cases)===
NM: 89.502 

and the results for each angle are:

[84.33692308 89.85384615 91.12230769 91.42153846 90.89076923 90.58769231
90.18384615 88.3        88.05384615 90.27461538 90.38692308 89.58
89.40307692 88.63846154].

We notice that the value of Rank@1(Including identical-view cases) is 89.9%, is there a transcription error?

**Comment by darkliang** [comment]
Hi, we recheck this result, and it still achieves 89.9%.
```
[2022-01-03 21:46:20] [INFO]: ===Rank-1 (Include identical-view cases)===
[2022-01-03 21:46:20] [INFO]: NM: 90.315 
[2022-01-03 21:46:20] [INFO]: ===Rank-1 (Exclude identical-view cases)===
[2022-01-03 21:46:20] [INFO]: NM: 89.935 
```
Maybe your data set is processed differently than ours?

**Comment by ctrasd** [comment]
Thank you for your reply. 

We processed the data with our own scripts for re-arrangement based on the _pretreatment.py_ given in GaitSet rather than the scripts given in this repository.  

Maybe there are some little differences in the processed data, we will follow the prepare steps strictly and test it again.

Thank you again for this excellent framework, it can boost the speed of training and testing obviously and helped us a lot.

**Comment by zhang123-sys** [comment]
Transforming:   0%|                                                                                                                                            | 0/1288 [00:00<?, ?it/s]Traceback (most recent call last):
  File "opengait/main.py", line 71, in <module>
    run_model(cfgs, training)
  File "opengait/main.py", line 56, in run_model
    Model.run_test(model)
  File "/hy-nas/OpenGait-master/opengait/modeling/base_model.py", line 441, in run_test
    info_dict = model.inference(rank)
  File "/hy-nas/OpenGait-master/opengait/modeling/base_model.py", line 380, in inference
    retval = self.forward(ipts)
  File "/hy-nas/OpenGait-master/opengait/modeling/models/gaitgl.py", line 156, in forward
    'The input size of each GPU must be 1 in testing mode, but got {}!'.format(len(labs)))
ValueError: The input size of each GPU must be 1 in testing mode, but got 2!
