### ISSUE TITLE
使用baseline模型进行测试时报错

### ISSUE THREAD

**Issue by SerJamie** [ShiqiYu/OpenGait#35]
## Detailed description
[2022-02-17 12:42:57] [INFO]: {'dataset_name': 'CASIA-B', 'dataset_root': './dataset_output', 'num_workers': 1, 'dataset_partition': './misc/partitions/CASIA-B_include_005.json', 'remove_no_gallery': False, 'cache': False, 'test_dataset_name': 'CASIA-B'}
[2022-02-17 12:42:57] [INFO]: -------- Test Pid List --------
[2022-02-17 12:42:57] [INFO]: ['075']
[2022-02-17 12:43:00] [INFO]: Restore Parameters from output/CASIA-B/Baseline/Baseline/checkpoints/Baseline-60000.pt !!!
[2022-02-17 12:43:00] [INFO]: Parameters Count: 3.77914M
[2022-02-17 12:43:00] [INFO]: Model Initialization Finished!
Transforming: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 110/110 [00:01<00:00, 76.67it/s]
Traceback (most recent call last):
  File "lib/main.py", line 70, in <module>
    run_model(cfgs, training)
  File "lib/main.py", line 55, in run_model
    Model.run_test(model)
  File "/home/lalaland/PycharmProjects/OpenGait_/lib/modeling/base_model.py", line 470, in run_test
    return eval_func(info_dict, dataset_name, **valid_args)
  File "/home/lalaland/PycharmProjects/OpenGait_/lib/utils/evaluation.py", line 79, in identification
    0) * 100 / dist.shape[0], 2)
ValueError: could not broadcast input array from shape (4,) into shape (5,)
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 10590) of binary: /home/lalaland/anaconda3/envs/torch/bin/python
Traceback (most recent call last):
  File "/home/lalaland/anaconda3/envs/torch/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/lalaland/anaconda3/envs/torch/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/lalaland/anaconda3/envs/torch/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/lalaland/anaconda3/envs/torch/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/lalaland/anaconda3/envs/torch/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/lalaland/anaconda3/envs/torch/lib/python3.7/site-packages/torch/distributed/run.py", line 713, in run
    )(*cmd_args)
  File "/home/lalaland/anaconda3/envs/torch/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/lalaland/anaconda3/envs/torch/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 261, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
lib/main.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-02-17_12:43:06
  host      : lalaland-Predator-PH317-55
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 10590)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by SerJamie** [comment]
想请问以下这一类错误该如何解决，网上相关资料似乎较少

**Comment by SerJamie** [comment]
pytorch=>1.9
cuda=>11.0
ubuntu=>18.04

**Comment by darkliang** [comment]
> [2022-02-17 12:42:57] [INFO]: ['075']

It seems you only used one subject for test, it must not work.

**Comment by SerJamie** [comment]
谢谢回答！我是该用多gpu进行一个运行是吗

**Comment by darkliang** [comment]
I mean you only have one test subject, it doesn't make sense, and we haven't considered that.

**Comment by SerJamie** [comment]
所以我该使用更多的例子进行测试是么，请问有没有个下限呢，比如大于50个？或者是按照124的标准来

**Comment by darkliang** [comment]
You need at least two subject.

**Comment by SerJamie** [comment]
谢谢大佬回复！
