### ISSUE TITLE
OUMVLP  test phase: Error(s) in loading state_dict for Baseline

### ISSUE THREAD

**Issue by jackhanyuan** [ShiqiYu/OpenGait#41]
## System information (version)
- torch  1.8.0
- Cuda  11.1

## Detailed description

Distributed init (rank 0): env://
[2022-03-10 11:42:57] [INFO]: {'enable_float16': False, 'restore_ckpt_strict': True, 'restore_hint': 150000, 'save_name': 'Baseline', 'eval_func': 'identification', 'sampler': {'batch_size': 4, 'sample_type': 'all_ordered', 'type': 'InferenceSampler', 'batch_shuffle': False, 'frames_all_limit': 720}, 'transform': [{'img_w': 64, 'type': 'BaseSilCuttingTransform'}], 'metric': 'euc'}
[2022-03-10 11:42:57] [INFO]: {'model': 'Baseline', 'backbone_cfg': {'in_channels': 1, 'layers_cfg': ['BC-32', 'BC-32', 'M', 'BC-64', 'BC-64', 'M', 'BC-128', 'BC-128', 'BC-256', 'BC-256'], 'type': 'Plain'}, 'SeparateFCs': {'in_channels': 256, 'out_channels': 256, 'parts_num': 31}, 'SeparateBNNecks': {'class_num': 5153, 'in_channels': 256, 'parts_num': 31}, 'bin_num': [16, 8, 4, 2, 1]}
[2022-03-10 11:42:58] [INFO]: {'dataset_name': 'OUMVLP', 'dataset_root': 'OUMVLP-pkl', 'dataset_partition': './misc/partitions/OUMVLP.json', 'num_workers': 1, 'remove_no_gallery': False, 'cache': False, 'test_dataset_name': 'OUMVLP'}

[2022-03-10 11:42:58] [INFO]: -------- Test Pid List --------
[2022-03-10 11:42:58] [INFO]: [00002, 00004, ..., 00022]
Traceback (most recent call last):
  File "D:/OpenGait/lib/my_main.py", line 111, in <module>
    mp.spawn(main,
  File "D:\Installations\ComputerScience\Python\Anaconda3\envs\gait\lib\site-packages\torch\multiprocessing\spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "D:\Installations\ComputerScience\Python\Anaconda3\envs\gait\lib\site-packages\torch\multiprocessing\spawn.py", line 188, in start_processes
    while not context.join():
  File "D:\Installations\ComputerScience\Python\Anaconda3\envs\gait\lib\site-packages\torch\multiprocessing\spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "D:\Installations\ComputerScience\Python\Anaconda3\envs\gait\lib\site-packages\torch\multiprocessing\spawn.py", line 59, in _wrap
    fn(i, *args)
  File "D:\OpenGait\lib\my_main.py", line 104, in main
    run_model(cfgs, training)
  File "D:\OpenGait\lib\my_main.py", line 64, in run_model
    model = Model(cfgs, training)
  File "D:\OpenGait\lib\modeling\base_model.py", line 168, in __init__
    self.resume_ckpt(restore_hint)
  File "D:\OpenGait\lib\modeling\base_model.py", line 289, in resume_ckpt
    self._load_ckpt(save_name)
  File "D:\OpenGait\lib\modeling\base_model.py", line 262, in _load_ckpt
    self.load_state_dict(model_state_dict, strict=load_ckpt_strict)
  File "D:\Installations\ComputerScience\Python\Anaconda3\envs\gait\lib\site-packages\torch\nn\modules\module.py", line 1482, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Baseline:
	size mismatch for BNNecks.fc_bin: copying a param with shape torch.Size([31, 256, 5154]) from checkpoint, the shape in current model is torch.Size([31, 256, 5153]).

**Comment by noahshen98** [comment]
hi, I found that this issue may be caused by mismatch setting of bnneck .

As you see: size mismatch for BNNecks.fc_bin: copying a param with shape torch.Size([31, 256, 5154]) from checkpoint, the shape in current model is torch.Size([31, 256, 5153]).

Check your training setting if classnum is 5153 in BNNeck

**Comment by noahshen98** [comment]
If you use our uploaded checkpoint, we will check if we upload the wrong checkpoints.

We will check it later. Thanks for your reminder:)

**Comment by jackhanyuan** [comment]
> If you use our uploaded checkpoint, we will check if we upload the wrong checkpoints.
> 
> We will check it later. Thanks for your reminder:)

Yes, I use your uploaded checkpoint.

**Comment by noahshen98** [comment]
> > If you use our uploaded checkpoint, we will check if we upload the wrong checkpoints.
> 
> > 
> 
> > We will check it later. Thanks for your reminder:)
> 
> 
> 
> Yes, I use your uploaded checkpoint. @noahshen98 

We just found it is our fault. We upload the wrong checkpoint for Baseline-OUMVLP.

Thank you again for reminder, we will upload the correct one later.

**Comment by darkliang** [comment]
@jackhanyuan Hi, we have updated the correct checkpoint. You can try it again.
