### ISSUE TITLE
Training yields: "AttributeError: 'PosixPath' object has no attribute 'startswith'"

### ISSUE THREAD

**Issue by Anjin-Byte** [ShiqiYu/OpenGait#87]
## System information (version)
- Pytorch => 1.6
- Operating System / Platform => Ubuntu 20.04 (WSL)
- Cuda => 11.7

## Detailed description

Running test.sh or train.sh causes exception:

Traceback (most recent call last):
  File "opengait/main.py", line 6, in <module>
    from modeling import models
  File "/home/[username]/CAPSTONE/OpenGait/opengait/modeling/models/__init__.py", line 9, in <module>
    for (_, module_name, _) in iter_modules([package_dir]):
  File "/usr/lib/python3.8/pkgutil.py", line 129, in iter_modules
    for i in importers:
  File "/usr/lib/python3.8/pkgutil.py", line 419, in get_importer
    importer = path_hook(path_item)
  File "<frozen importlib._bootstrap_external>", line 1594, in path_hook_for_FileFinder
  File "<frozen importlib._bootstrap_external>", line 1469, in __init__
  File "<frozen importlib._bootstrap_external>", line 177, in _path_isabs
AttributeError: 'PosixPath' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/usr/lib/python3.8/pkgutil.py", line 415, in get_importer
    importer = sys.path_importer_cache[path_item]
KeyError: PosixPath('/home/[username]/CAPSTONE/OpenGait/opengait/modeling/models')

"AttributeError: 'PosixPath' object has no attribute 'startswith'"
I believe this is the key clue to the issue but all I can find online is references to a package (Faker) which is neither needed or installed. 

## Issue submission checklist
I've seen this same issue posted a few weeks back by @zhang123-sys. The only suggestion was to upgrade to python3.9 which has not worked for me the other user.

**Comment by darkliang** [comment]
duplicate with issue #69

**Comment by HUAFOR** [comment]
你好，这个问题我昨天在恒源云训练机器时候遇到过，最后解决，大概率是因为python3.8的问题导致的bug，
在这里我提供我自己的解决方式,希望对你有帮助！：
到目录/lib/python3.8/pkgutli.py下找到：
try:
       importer = sys.path_importer_cache[path_item]
在这段话前面添加一行：
path_item = os.fsdecode(path_item)
即可解决。
![image](https://user-images.githubusercontent.com/58834906/219601125-4022dc5d-2846-45a2-a3a1-a701660de29d.png)
参考链接：https://github.com/python/cpython/commit/4844abdd700120120fc76c29d911bcb547700baf
