### ISSUE TITLE
A error when training GaitEdge

### ISSUE THREAD

**Issue by enemy1205** [ShiqiYu/OpenGait#91]
## System information (version)
- Pytorch => :1.10
- Operating System / Platform => :Ubuntu 20.04
- Cuda => :11.7

## Detailed description
```
[2022-10-13 11:26:52] [INFO]: {'enable_float16': True, 'with_test': True, 'fix_BN': False, 'log_iter': 100, 'restore_ckpt_strict': False, 'optimizer_reset': True, 'scheduler_reset': True, 'restore_hint': 0, 'save_iter': 500, 'save_name': 'GaitEdge', 'sync_BN': True, 'total_iter': 5000, 'sampler': {'batch_shuffle': True, 'batch_size': [6, 6], 'frames_num_fixed': 30, 'frames_num_max': 50, 'frames_num_min': 25, 'sample_type': 'fixed_ordered', 'type': 'TripletSampler', 'frames_skip_num': 0}, 'transform': [{'type': 'NoOperation'}, {'type': 'BaseRgbTransform'}, {'type': 'BaseSilTransform'}]}
[2022-10-13 11:26:52] [INFO]: {'model': 'GaitEdge', 'GaitGL': {'channels': [32, 64, 128], 'class_num': 74}, 'Segmentation': {'type': 'U_Net', 'in_channels': 3, 'freeze_half': True}, 'edge': True, 'align': True, 'seg_lr': 1e-05, 'kernel_size': 3}
[2022-10-13 11:26:53] [INFO]: {'dataset_name': 'CASIA-B*', 'dataset_root': '/home/lxc/lxc/dataset/casiab-128-end2end', 'num_workers': 8, 'dataset_partition': './datasets/CASIA-B*/CASIA-B*.json', 'remove_no_gallery': False, 'cache': False, 'test_dataset_name': 'CASIA-B', 'data_in_use': [False, True, True, True]}
[2022-10-13 11:26:53] [INFO]: -------- Train Pid List --------
[2022-10-13 11:26:53] [INFO]: [001, 002, ..., 074]
[2022-10-13 11:26:53] [INFO]: -------- Test Pid List --------
[2022-10-13 11:26:53] [INFO]: [075, 076, ..., 124]
[2022-10-13 11:26:53] [INFO]: {'lr': 0.0001, 'momentum': 0.9, 'solver': 'Adam', 'weight_decay': 0.0005}
[2022-10-13 11:26:53] [INFO]: {'gamma': 0.1, 'milestones': [10000], 'scheduler': 'MultiStepLR'}
[2022-10-13 11:26:53] [INFO]: Parameters Count: 3.63410M
[2022-10-13 11:26:53] [INFO]: Model Initialization Finished!
[2022-10-13 11:29:29] [INFO]: Iteration 00100, Cost 157.30s, triplet_loss=0.2062, triplet_hard_loss=0.7473, triplet_loss_num=4412.1572, triplet_mean_dist=0.5779, softmax_loss=4.3196, softmax_accuracy=0.0109, bce_loss=0.9149, bce_hard_loss=20.7233, bce_miou=0.2942
[2022-10-13 11:31:51] [INFO]: Iteration 00200, Cost 142.13s, triplet_loss=0.2016, triplet_hard_loss=0.7628, triplet_loss_num=4053.8328, triplet_mean_dist=0.6384, softmax_loss=4.3228, softmax_accuracy=0.0163, bce_loss=0.7388, bce_hard_loss=20.7233, bce_miou=0.3602
[2022-10-13 11:34:11] [INFO]: Iteration 00300, Cost 139.68s, triplet_loss=0.2000, triplet_hard_loss=0.7823, triplet_loss_num=3731.9873, triplet_mean_dist=0.7054, softmax_loss=4.3189, softmax_accuracy=0.0107, bce_loss=0.6242, bce_hard_loss=20.7233, bce_miou=0.4177
[2022-10-13 11:36:41] [INFO]: Iteration 00400, Cost 150.40s, triplet_loss=0.2013, triplet_hard_loss=0.8047, triplet_loss_num=3468.4976, triplet_mean_dist=0.7407, softmax_loss=4.2988, softmax_accuracy=0.0186, bce_loss=0.5506, bce_hard_loss=20.7233, bce_miou=0.4826
[2022-10-13 11:39:01] [INFO]: Iteration 00500, Cost 139.91s, triplet_loss=0.2012, triplet_hard_loss=0.8172, triplet_loss_num=3214.1606, triplet_mean_dist=0.7616, softmax_loss=4.3094, softmax_accuracy=0.0094, bce_loss=0.5010, bce_hard_loss=20.7233, bce_miou=0.5453
[2022-10-13 11:39:03] [INFO]: Running test...

Transforming:   0%|          | 0/5496 [00:00<?, ?it/s]Traceback (most recent call last):
  File "opengait/main.py", line 71, in <module>
    run_model(cfgs, training)
  File "opengait/main.py", line 54, in run_model
    Model.run_train(model)
  File "/root/autodl-tmp/lxc/OpenGait/opengait/modeling/base_model.py", line 424, in run_train
    result_dict = BaseModel.run_test(model)
  File "/root/autodl-tmp/lxc/OpenGait/opengait/modeling/base_model.py", line 439, in run_test
    info_dict = model.inference(rank)
  File "/root/autodl-tmp/lxc/OpenGait/opengait/modeling/base_model.py", line 378, in inference
    retval = self.forward(ipts)
  File "/root/autodl-tmp/lxc/OpenGait/opengait/modeling/models/gaitedge.py", line 133, in forward
    retval = super(GaitEdge, self).forward(
  File "/root/autodl-tmp/lxc/OpenGait/opengait/modeling/models/gaitgl.py", line 155, in forward
    raise ValueError(
ValueError: The input size of each GPU must be 1 in testing mode, but got 4!
```
When it runs for the number of save_iter(500) I set, it throws such an error.
```
trainer_cfg:
  enable_float16: true # half_percesion float for memory reduction and speedup
  with_test: true
  log_iter: 100
  restore_ckpt_strict: false
  optimizer_reset: true
  scheduler_reset: true
  sync_BN: true
  restore_hint: 0
    # - Segmentation-30000.pt
    # - GaitGL-80000.pt
  save_iter: 500
  save_name: GaitEdge
  total_iter: 5000
  sampler:
    batch_shuffle: true
    batch_size:
      - 6 # TripletSampler, batch_size[0] indicates Number of Identity
      - 6 #                 batch_size[1] indicates Samples sequqnce for each Identity
    frames_num_fixed: 30
    frames_skip_num: 0
    sample_type: fixed_ordered
    type: TripletSampler
  transform:
    - type: NoOperation
    - type: BaseRgbTransform
    - type: BaseSilTransform

```
It was supposed to be a problem in the testing phase

Besides,I also met the problem when I tend to train on multi-cuda device so that I have to train on single GPU.
```
RuntimeError: All input tensors must be on the same device. Received cuda:0 and cuda:1
```

**Comment by darkliang** [comment]
What is `batch_size` in evaluator_cfg and how many GPUs you use?
`ValueError: The input size of each GPU must be 1 in testing mode, but got 4!` means that two nums are different.

**Comment by enemy1205** [comment]
Thanks for your reply.
And I still don't understand the problem when i use the DistributedDataParallel on 2 GPUs
I run the shell script like this:
`CUDA_VISIBLE_DEVICES=1,4  python -m torch.distributed.launch --nproc_per_node=2 opengait/main.py --cfgs ./configs/gaitedge/phase2_gaitedge.yaml --phase train`

And it will throw such an error:
```
Traceback (most recent call last):
  File "opengait/main.py", line 71, in <module>
    run_model(cfgs, training)
  File "opengait/main.py", line 54, in run_model
    Model.run_train(model)
  File "/root/autodl-tmp/lxc/OpenGait/opengait/modeling/base_model.py", line 404, in run_train
    retval = model(ipts)
  File "/root/autodl-tmp/lxc/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/autodl-tmp/lxc/miniconda3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1008, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/root/autodl-tmp/lxc/miniconda3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 969, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/root/autodl-tmp/lxc/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/autodl-tmp/lxc/OpenGait/opengait/modeling/models/gaitedge.py", line 115, in forward
    edge_mask, eroded_mask = self.preprocess(sils)
  File "/root/autodl-tmp/lxc/OpenGait/opengait/modeling/models/gaitedge.py", line 94, in preprocess
    dilated_mask = (morph.dilation(sils, self.kernel).detach()
  File "/root/autodl-tmp/lxc/miniconda3/lib/python3.8/site-packages/kornia/morphology/morphology.py", line 94, in dilation
    output, _ = torch.max(output + neighborhood.flip((0, 1)), 4)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0!
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 179527 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 179528) of binary: /root/autodl-tmp/lxc/miniconda3/bin/python
```

**Comment by darkliang** [comment]
The problem should be that `sils` and `kernel` are not on the same device. This should be a bug in our code and I will fix it asap.

**Comment by enemy1205** [comment]
Thank you very much for your prompt reply！
