### ISSUE TITLE
Sampler is getting index out of bounds

### ISSUE THREAD

**Issue by gosiqueira** [ShiqiYu/OpenGait#95]
## System information (version)
- Pytorch: 1.12.1
- Cuda: 10.2
- CuDNN: 7.6.5
- OS: Ubuntu 20.04.4 LTS

## Detailed description

I'm trying to reproduce the training phase for current methods described in the model zoo for a study regarding state-of-the-art methods for Gait Recognition. Currently I'm trying to execute the `baseline` model. However, when I execute the script provided for training I get the following error:

```bash
/apps/conda/gustavo.siqueira/.envs/opengait/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
[2022-11-17 18:21:30] [INFO]: {'enable_float16': True, 'with_test': True, 'fix_BN': False, 'log_iter': 100, 'restore_ckpt_strict': True, 'optimizer_reset': False, 'scheduler_reset': False, 'restore_hint': 0, 'save_iter': 10000, 'save_name': 'Baseline', 'sync_BN': True, 'total_iter': 60000, 'sampler': {'batch_shuffle': True, 'batch_size': [8, 16], 'frames_num_fixed': 30, 'frames_num_max': 50, 'frames_num_min': 25, 'sample_type': 'fixed_unordered', 'type': 'TripletSampler'}, 'transform': [{'type': 'BaseSilCuttingTransform', 'img_w': 64}]}
[2022-11-17 18:21:30] [INFO]: {'model': 'Baseline', 'backbone_cfg': {'in_channels': 1, 'layers_cfg': ['BC-64', 'BC-64', 'M', 'BC-128', 'BC-128', 'M', 'BC-256', 'BC-256'], 'type': 'Plain'}, 'SeparateFCs': {'in_channels': 256, 'out_channels': 256, 'parts_num': 31}, 'SeparateBNNecks': {'class_num': 74, 'in_channels': 256, 'parts_num': 31}, 'bin_num': [16, 8, 4, 2, 1]}
[2022-11-17 18:21:30] [INFO]: {'dataset_name': 'CASIA-B', 'dataset_root': '/storage/datasets/gait/CASIA/CASIA-B-pkl', 'num_workers': 1, 'dataset_partition': './datasets/CASIA-B/CASIA-B_include_005.json', 'remove_no_gallery': False, 'cache': False, 'test_dataset_name': 'CASIA-B'}
[2022-11-17 18:21:30] [INFO]: -------- Train Pid List --------
[2022-11-17 18:21:30] [INFO]: []
[2022-11-17 18:21:30] [INFO]: -------- Test Pid List --------
[2022-11-17 18:21:30] [INFO]: []
[2022-11-17 18:21:32] [INFO]: {'lr': 0.1, 'momentum': 0.9, 'solver': 'SGD', 'weight_decay': 0.0005}
[2022-11-17 18:21:32] [INFO]: {'gamma': 0.1, 'milestones': [20000, 40000], 'scheduler': 'MultiStepLR'}
[2022-11-17 18:21:32] [INFO]: Parameters Count: 3.77914M
[2022-11-17 18:21:32] [INFO]: Model Initialization Finished!
Traceback (most recent call last):
  File "opengait/main.py", line 73, in <module>
Traceback (most recent call last):
  File "opengait/main.py", line 73, in <module>
    run_model(cfgs, training)
  File "opengait/main.py", line 56, in run_model
    Model.run_train(model)
  File "/mnt/users/gustavo.siqueira/codes/gait-benchmarks/OpenGait/opengait/modeling/base_model.py", line 403, in run_train
    for inputs in model.train_loader:
  File "/apps/conda/gustavo.siqueira/.envs/opengait/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 444, in __iter__
    return self._get_iterator()
  File "/apps/conda/gustavo.siqueira/.envs/opengait/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 390, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/apps/conda/gustavo.siqueira/.envs/opengait/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1115, in __init__
    self._reset(loader, first_iter=True)
  File "/apps/conda/gustavo.siqueira/.envs/opengait/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1148, in _reset
    self._try_put_index()
  File "/apps/conda/gustavo.siqueira/.envs/opengait/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1382, in _try_put_index
    index = self._next_index()
  File "/apps/conda/gustavo.siqueira/.envs/opengait/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 671, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/mnt/users/gustavo.siqueira/codes/gait-benchmarks/OpenGait/opengait/data/sampler.py", line 26, in __iter__
    pid_list = sync_random_sample_list(
  File "/mnt/users/gustavo.siqueira/codes/gait-benchmarks/OpenGait/opengait/data/sampler.py", line 54, in sync_random_sample_list
    idx = random.choices(range(len(obj_list)), k=k)
  File "/apps/conda/gustavo.siqueira/.envs/opengait/lib/python3.8/random.py", line 399, in choices
    return [population[_int(random() * n)] for i in _repeat(None, k)]
  File "/apps/conda/gustavo.siqueira/.envs/opengait/lib/python3.8/random.py", line 399, in <listcomp>
    return [population[_int(random() * n)] for i in _repeat(None, k)]
IndexError: range object index out of range
    run_model(cfgs, training)
  File "opengait/main.py", line 56, in run_model
    Model.run_train(model)
  File "/mnt/users/gustavo.siqueira/codes/gait-benchmarks/OpenGait/opengait/modeling/base_model.py", line 403, in run_train
    for inputs in model.train_loader:
  File "/apps/conda/gustavo.siqueira/.envs/opengait/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 444, in __iter__
    return self._get_iterator()
  File "/apps/conda/gustavo.siqueira/.envs/opengait/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 390, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/apps/conda/gustavo.siqueira/.envs/opengait/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1115, in __init__
    self._reset(loader, first_iter=True)
  File "/apps/conda/gustavo.siqueira/.envs/opengait/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1148, in _reset
    self._try_put_index()
  File "/apps/conda/gustavo.siqueira/.envs/opengait/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1382, in _try_put_index
    index = self._next_index()
  File "/apps/conda/gustavo.siqueira/.envs/opengait/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 671, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/mnt/users/gustavo.siqueira/codes/gait-benchmarks/OpenGait/opengait/data/sampler.py", line 26, in __iter__
    pid_list = sync_random_sample_list(
  File "/mnt/users/gustavo.siqueira/codes/gait-benchmarks/OpenGait/opengait/data/sampler.py", line 54, in sync_random_sample_list
    idx = random.choices(range(len(obj_list)), k=k)
  File "/apps/conda/gustavo.siqueira/.envs/opengait/lib/python3.8/random.py", line 399, in choices
    return [population[_int(random() * n)] for i in _repeat(None, k)]
  File "/apps/conda/gustavo.siqueira/.envs/opengait/lib/python3.8/random.py", line 399, in <listcomp>
    return [population[_int(random() * n)] for i in _repeat(None, k)]
IndexError: range object index out of range
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 68889) of binary: /apps/conda/gustavo.siqueira/.envs/opengait/bin/python
Traceback (most recent call last):
  File "/apps/conda/gustavo.siqueira/.envs/opengait/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/apps/conda/gustavo.siqueira/.envs/opengait/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/apps/conda/gustavo.siqueira/.envs/opengait/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/apps/conda/gustavo.siqueira/.envs/opengait/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/apps/conda/gustavo.siqueira/.envs/opengait/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/apps/conda/gustavo.siqueira/.envs/opengait/lib/python3.8/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/apps/conda/gustavo.siqueira/.envs/opengait/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/apps/conda/gustavo.siqueira/.envs/opengait/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
opengait/main.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2022-11-17_18:21:35
  host      : viper02
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 68890)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-11-17_18:21:35
  host      : viper02
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 68889)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
srun: error: viper02: task 0: Exited with exit code 1
/apps/conda/gustavo.siqueira/.envs/opengait/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions
```

## Steps to reproduce

I simply executed the `train.sh` script on a [Slurm](https://slurm.schedmd.com/documentation.html) cluster. I modified the `CUDA_VISIBLE_DEVICES` flag given Slurm job policy, but I don't believe this is causing the issue.

## Issue submission checklist
 - [x] I checked the problem with documentation, FAQ, issues, and have not found solution.

**Comment by ChaoFan996** [comment]
Hi, check the dataset_root please.
Both the train and test pid list in your log are empty list, i.e., [].

**Comment by gosiqueira** [comment]
Root was fine. It seems that I had an error preprocessing the CASIA database, causing the folder to be empty. I apologize for the lame issue and I'm closing it with this comment.
Thanks once again.
