### ISSUE TITLE
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1646755953518/work/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1102, internal error, NCCL version 21.0.3

### ISSUE THREAD

**Issue by King-Endeavor** [ShiqiYu/OpenGait#96]
## System information (version)

- Pytorch => :grey_question:
- Operating System / Platform => :grey_question:
- Cuda => :grey_question:

## Detailed description
I successfully run the codes on GTX3080ti， but when I run the codes on the other server with two GTX3060, it failed.

The error occured.

Traceback (most recent call last):
  File "opengait/main.py", line 71, in <module>
    run_model(cfgs, training)
  File "opengait/main.py", line 49, in run_model
    model = get_ddp_module(model)
  File "/home/fengyuxiang/OpenGait-master/opengait/utils/common.py", line 199, in get_ddp_module
    find_unused_parameters=False, **kwargs)
  File "/home/fengyuxiang/anaconda3/envs/OpenGait/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 641, in __init__
    dist._verify_params_across_processes(self.process_group, parameters)
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1646755953518/work/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1102, internal error, NCCL version 21.0.3
ncclInternalError: Internal check failed. This is either a bug in NCCL or due to memory corruption

## Issue submission checklist
 - [ ] I checked the problem with documentation, FAQ, issues, and have not found solution.

**Comment by darkliang** [comment]
I don't think this problem is related to OpenGait, you may need to go to nccl's community for help.
